services:
  redis:
    image: "redis:latest"
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: url_shortener
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
